spring.application.name=portal

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/citizen}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root@123}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:9000}

file.upload-dir=uploads