spring.application.name=portal

spring.datasource.url=jdbc:mysql://localhost:3306/citizen
spring.datasource.username=root
spring.datasource.password=root@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=9000

file.upload-dir=uploads